# Version of docker-compose
version: '3'

# Containers we are going to run
services:
  # Our Phoenix container
  phoenix:
    # The build parameters for this container.
    build: ./Phoenix
    # Container name
    container_name: phoenix
    environment:
      # Variables to connect to our Postgres server
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: postgres
      PGPORT: 5432
      # Hostname of our Postgres container
      PGHOST: db
    ports:
      # Mapping the port to make the Phoenix app accessible outside of the container
      - "4000:4000"
    depends_on:
      # The db container needs to be started before we start this container
      - db
  db:
    # We use the predefined Postgres image
    image: postgres:9.6
    # Container name
    container_name: postgres
    environment:
      # Set user/password for Postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      SECRET_KEY_BASE: "U5VAUksET3qmO6zrS4nPTEE+uGa/2z11b7bKsnhejIyIVhLviJyU8drffTg9n6Wv"
      # Set a path where Postgres should store the data
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
  vuejs:
    # The build parameters for this container.
    build: ./vuejs
    # Container name
    container_name: vuejs
    ports:
      # Mapping the port to make the Vue js app accessible outside of the container
      - "8080:8080"
    depends_on:
      - phoenix
# Define the volumes
volumes:
  pgdata: